### ISSUE TITLE
Please add a tile for t_floor_primitive

### ISSUE THREAD

**Issue by hexagonrecursion** [CDDA-Tilesets/UltimateCataclysm-src#1]
This tile is used by faction camps

![DeepinScreenshot_select-area_20220104221454](https://user-images.githubusercontent.com/52621858/148111768-04aae6f8-2e06-4b05-8296-3b1d65393b87.png)

**Comment by int-ua** [comment]
The correct repository is at https://github.com/I-am-Erk/CDDA-Tilesets this was just an experiment that no one else supported

**Comment by hexagonrecursion** [comment]
IMHO you should update the README and descriptions of the three repositories under https://github.com/CDDA-Tilesets to link to https://github.com/I-am-Erk/CDDA-Tilesets and then archive them. This will help avoid such confusion in the future.
